#!/bin/bash

echo 
echo "    ################         ####   ####               ## "
echo "    ################      ####      ####               ## "          
echo "    ################     ###        ####               ## "
echo "         ####           ###         ####               ## "
echo "         ####          ###          ####               ## "
echo "         ####         ###           ####               ## "
echo "         ####         ###           ####               ## "
echo "         ####         ###           ####               ######            ####     ##       ## "
echo "         ####          ###          ####               ##    ###        ##   ##     ##   ## "
echo "         ####          ###          ####               ##      ##      ##     ##      ### "
echo "         ####           ##          ##############     ##       ##     ##     ##      ### "
echo "         ####            ####       ##############     ##      ##       ##   ##     ##   ## "
echo "         ####              #####    ##############     #########         #####    ##       ## "
echo
echo
echo " An Intellectual user Interface that will convert the constarints in .csv file format to sdc format,"
echo "   and with help of TOOL YOSYS and Opentimer generate the detailed report of synthesized"
echo "                              netlist and prelayout time report."
echo "            Developed and maintained by the Design verification Engineer Reshu Saini "
echo "            For any queries and bugs please report on the mail: reshu.1712@gmail.com "
echo
---------Tool Initialization---------
-------------------------------------
if [ $# -eq 0 ]; then
	echo "Info: Please provide the csv file"
	exit 1
elif [ $# -gt 1 ] && [ $1 != *.csv ]; then
	echo "Info: Please provide only one csv file"
	exit 1
else
	if [[ $1 != *.csv ]] && [ $1 != "-help" ]; then
		echo "Info: Please provide a .csv format file"
		exit 1
	fi
fi

if [ ! -e $1 ] || [ $1 == "-help" ]; then
	if [ $1 != "-help" ]; then
		echo "Error: Cannot find csv file $1. Exiting..."
		exit 1
	else
		echo "USAGE:  ./TCLbox <csv file>"
		echo
		echo "        where <csv file> consists of 2 columns, below keyword being in 1st column and is Case Sensitive. Please request Reshu for sample csv file."
		echo
		echo "        <Design Name> is the name of top level module."
		echo
		echo "        <Output Directory> is the name of output directory where you want to dump synthesis script, synthesized netlist and timing reports."
		echo
		echo "        <Netlist Directory> is the name of directory where all RTL netlist are present."
		echo
		echo "        <Early Library Path> is the file path of the early cell library to be used for STA."
		echo
		echo "        <Late Library Path> is file path of the late cell library to be used for STA."
		echo
		echo "        <Constraints file> is csv file path of constraints to be used for STA."
		echo
	fi
else
	echo "Info: csv file $1 accepted"
	tclsh TCLbox.tcl $1
fi 
